nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:3000"]
    allow_methods: ["GET", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: []
    max_age: 3600
    allow_credentials: false

  paths:
    "^/sent/front":
      allow_origin: ["http://localhost:3000"]
      allow_methods: ["GET", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
